version: "3.3"
services:
  simulation:
    build:
      context: .
      dockerfile: Simulation.Dockerfile
    image: eu.gcr.io/temporal-dynamics/simulation:latest
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    image: eu.gcr.io/temporal-dynamics/app:latest
    environment:
      PORT: 8051 # for local runs
    ports:
      - "8051:8051"
