version: "3.3"
services:
  simulation:
    build:
      context: .
      dockerfile: Simulation.Dockerfile
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
    environment:
      PORT: 8051 # for local runs
    ports:
      - "8051:8051"
