metadata:
  - machine_version
# input types: continuous, distribution, categorical, boolean
input:
  DATASET:
    type: categorical
    options: dataset.json
    default_index: 2
  ITERATIONS:
    type: continuous
    range: { min: 1 }
  infection_model:
    type: categorical
    options: [1, 2]
    default_index: 1
  number_of_patient_zero:
    type: continuous
    range: { min: 1 }
  D_min:
    type: continuous
    range: { step: 5, min: 0 }
  D_max:
    type: continuous
    range: { step: 60, min: 60, max: 1440 }
  P_max:
    type: continuous
    range: { step: 0.1, min: 0.1, max: 1.0 }
extra_input:
  alpha_blue:
    type: continuous
    range: { min: 0.0, max: 1.0, step: 0.1 }
  blue_to_white:
    type: distribution
    dist_type: normal
  purple_to_red:
    type: distribution
    dist_type: normal
  red_to_final_state:
    type: distribution
    dist_type: normal
  P_r:
    type: distribution
    dist_type: normal
hidden:
  age_dist:
    type: distribution
    dist_type: percent
