metadata:
  - machine_version
input:
  continuous:
    number_of_patient_zero: { min: 1 }
    alpha_blue: { min: 0.0, max: 1.0, step: 0.1 }
    D_min: { step: 5, min: 0 }
    D_max: { step: 60, min: 60, max: 1440 }
    P_max: { step: 0.1, min: 0.1, max: 1.0 }
    ITERATIONS: { min: 1 }
  distribution:
    blue_to_white: normal
    purple_to_red: normal
    red_to_final_state: normal
    P_r: normal
    age_dist: percent
  categorical:
    infection_model: 1
    DATASET: 2
  boolean:
    - SENSITIVITY
