metadata:
  - machine_version
# input types: continuous, distribution, categorical, boolean
input:
  DATASET:
    type: categorical
    options: datasets.yaml
    default_index: 2
  ITERATIONS:
    type: continuous
    range: { min: 1 }
  infection_model:
    type: categorical
    options: [1, 2, "wells_riley"]
    default_index: 1
  country:
    type: categorical
    options:
      - United Kingdom
      - Israel
      - Belgium
      - Switzerland
      - Italy
      - Germany
      - Norway
      - Portugal
      - Czech Republic
    default_index: 0
  number_of_patient_zero:
    type: continuous
    range: { min: 1 }
  D_min:
    type: continuous
    range: { step: 5, min: 0 }
  D_max:
    type: continuous
    range: { step: 60, min: 60, max: 1440 }
  P_max:
    type: continuous
    range: { step: 0.1, min: 0.1, max: 1.0 }
extra_input:
  alpha_blue:
    type: continuous
    range: { min: 0.0, max: 1.0, step: 0.1 }
hidden:
  age_dist:
    type: distribution
    dist_type: percent
