settings:
  UPLOAD: false
  VERBOSE: false

meta:
  ITERATIONS: 5
  DATASET: random_undirected_concated_1000_1
  SENSITIVITY: true

params:
  divide: 1
  infection_model: VariantInfection
  variants: [delta, omicron]
  j: 0
  P_max: [0.001, 0.0012]
  immunity: [1.0, 0.0]
  reinfect: 1

sensitivity:
  params:
    - immunity
  metrics:
    - grouping: sick
      # cumsum: true
  ranges:
    immunity: { step: 0.8, min: 0.1, max: 0.9 }
