settings:
  UPLOAD: true
  VERBOSE: false
  ITER_DATASET: false


meta:
  ITERATIONS: 200
  DATASET: copenhagen_agg
  SENSITIVITY: true

params:
  divide: 1
  infection_model: GroupInfection
  # variants: [slower, faster]
  number_of_patient_zero: 1
  D_min: 0
  # P_max: [0.001, 0.001]
  # immunity: [0.0, 0.0]
  reinfect: 0
  split: 1

sensitivity:
  change: default # both, first, second, default
  params:
    - D_min
  metrics:
    - grouping: sick
    - grouping: daily_infected
      cumsum: true
    - grouping: not_green
  ranges:
    D_min: { step: 5, min: 5, max: 150}