settings:
  UPLOAD: true
  VERBOSE: false
  ITER_DATASET: false

meta:
  ITERATIONS: 200
  DATASET: random_undirected_concated_1000_1
  SENSITIVITY: false

params:
  divide: 1
  infection_model: VariantInfection
  variants: [slow, medium, fast]
  number_of_patient_zero: 1
  D_min: 0
  P_max: [0.1, 0.12, 0.14]
  immunity: [0.0, 0.0, 0.0]
  reinfect: 1

sensitivity:
  change: columns # matrix, rows, columns, default
  params:
    - immunity
  ranges:
    immunity: { step: 1.0, min: 0, max: 1}

visualize:
  how:
    - detailed
    # - summary
  metrics:
    - grouping: sick
    - grouping: daily_infected
      cumsum: true