settings:
  PARALLEL: false # run simulation in parallel, rather than iteratively. iterative seems to run faster locally
  # LOCAL: true # should be true if running locally, false if running in the cloud
  LOCAL_TASK: true # task list according to local config only. skips downloading task list from google cloud
  UPLOAD: true # upload results to google cloud
  SKIP_TESTS: true # skip heavy tests - google cloud and sql
  VERBOSE: false # how much to print
  INCREMENT: false # ask before continuing after each day - useful for heavy workloads

meta:
  DATASET: copenhagen_groups
  ITERATIONS: 200 # run experiment X times, so to average stochasticity. use 1 repetition for working on the model itself
  SENSITIVITY: true

params:
  country: United Kingdom
  number_of_patient_zero: 1
  patient_zeroes_on_days: [0]
  infection_model: 2 # [1, 2, 3, wells_riley]
  alpha_blue: 1.0 # if alpha_blue == 1.0 it will be skipped. float!
  # max_group_size: 5
  # max_duration: 60
  D_min: 5 # Arbitrary, The minimal threshold (in time) for infection,
  D_max: 200 # Arbitrary
  P_max: 0.5 # The probability to be infected when the exposure is over the threshold
  p: 0.5106 # ((7.72 + 9.30) / 2) * 0.001 * 60
  q: 1000
  Q: 900
  k: 3
  skew: 0

paths:
  green:
    children:
      - blue
      - purple
    distribution:
      - 0.75
      - 0.25
  blue:
    duration: [7.5, 1]
    children: [white]
  purple:
    children:
      - purple_pink
      - purple_red
    distribution:
      - 0.8
      - 0.2
  purple_pink:
    duration: [2.5, 0.5]
    children: [pink]
  purple_red:
    duration: [2.5, 0.5]
    children: [red]
  pink:
    duration: [10, 1]
    children: [white]
  red:
    children:
      - stable
      - intensive_care
    distribution: [0.5, 0.5]
  stable:
    children:
      - stable_white
      - stable_black
    distribution: [0.5, 0.5]
  stable_white:
    duration: [10, 1]
    children: [white]
  stable_black:
    duration: [10, 1]
    children: [black]
  intensive_care:
    children:
      - intensive_care_white
      - intensive_care_black
    distribution: [0.5, 0.5]
  intensive_care_white:
    duration: [10, 1]
    children: [white]
  intensive_care_black:
    duration: [10, 1]
    children: [black]
  white: {}
  black: {}

sensitivity:
  params:
    # - P_max
    # - skew
    - D_min
    # - blue
    # - red
  metrics:
    - grouping: sick # a color, sick, infectors or infected
      # percent: 20
      # amount: null
      # max_: true
      how: amount # day
    - grouping: infected
      how: amount
    # - grouping: sick
    #   how: day
    - grouping: not_green
      how: amount
    # - grouping: r_0

  ranges:
    D_min: { step: 5, min: 5, max: 200 }
    D_max: { step: 60, min: 1200, max: 1440 }
    P_max: { step: 0.1, min: 0.3, max: 0.7 }
    number_of_patient_zero: { step: 5, min: 5, max: 15 }
    skew: { step: 3, min: 0, max: 30 }
    ITERATIONS: { step: 5, min: 5, max: 20 }
    alpha_blue: { step: 0.1, min: 0.0, max: 1.0 }
    max_group_size: { step: 2, min: 1000, max: 1000 }
    red: { step: 0.1, min: 0.1, max: 0.3 }
    purple_pink: { step: 0.5, min: 2, max: 3 }
    blue: { step: 0.5, min: 7, max: 8 }
    #TODO add parameters for duration and distribution in state for blue, purple, red, pink...
