settings:
  UPLOAD: false
  VERBOSE: false
  ITER_DATASET: false


meta:
  ITERATIONS: 2
  DATASET: copenhagen_agg
  SENSITIVITY: true

params:
  divide: 1
  infection_model: GroupInfection
  # variants: [slower, faster]
  number_of_patient_zero: 1
  D_min: 0
  j: 0
  P_max: 0.5 #[0.001, 0.001]
  # immunity: [0.0, 0.0]
  # reinfect: 1


sensitivity:
  change: second # both, first, second, default
  params:
    - D_min
  metrics:
    - grouping: sick
    - grouping: daily_infected
      cumsum: true
  ranges:
    D_min: { step: 10, min: 5, max: 95}