settings:
  UPLOAD: false
  VERBOSE: false

meta:
  ITERATIONS: 30
  DATASET: random_undirected_concated_1000_1
  SENSITIVITY: true

params:
  divide: 1
  infection_model: VariantInfection
  variants: [slower, faster]
  number_of_patient_zero: 1
  j: 0
  P_max: [0.001, 0.0012]
  immunity: [0.0, 0.0]
  reinfect: 1


sensitivity:
  params:
    - immunity
  metrics:
    - grouping: sick
    - grouping: daily_infected
      cumsum: true
  ranges:
    immunity: { step: 0.05, min: 0.0, max: 1.0 }
