settings:
  UPLOAD: true

meta:
  ITERATIONS: 50
  DATASET: copenhagen_agg
  SENSITIVITY: true

params:
  divide: 2
  infection_model: GroupInfection
  variant_a:
    j: 1
    number_of_patient_zero: 1
    patient_zeroes_on_days: [0]
    P_max: 0.5
  randomize:
    - duration
    - datetime

sensitivity:
  params:
    - intensive_care_black
  metrics:
    - grouping: sick
  ranges:
    intensive_care_black: { step: 0.1, min: 9, max: 11 }
