settings:
  PARALLEL: false # run simulation in parallel, rather than iteratively. iterative seems to run faster locally
  # LOCAL: true # should be true if running locally, false if running in the cloud
  LOCAL_TASK: true # task list according to local config only. skips downloading task list from google cloud
  UPLOAD: false # upload results to google cloud
  SKIP_TESTS: true # skip heavy tests - google cloud and sql
  VERBOSE: true # how much to print
  INCREMENT: false # ask before continuing after each day - useful for heavy workloads

meta:
  DATASET: copenhagen_hops
  ITERATIONS: 3 # run experiment X times, so to average stochasticity. use 1 repetition for working on the model itself
  SENSITIVITY: false

params:
  country: United Kingdom
  number_of_patient_zero: 10
  patient_zeroes_on_days: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  # randomize_patient_zero:
  infection_model: 2 # [1, 2, wells_riley]
  alpha_blue: 1.0 # if alpha_blue == 1.0 it will be skipped. float!
  D_min: 0 # Arbitrary, The minimal threshold (in time) for infection,
  D_max: 60 # Arbitrary
  P_max: 1.0 # The probability to be infected when the exposure is over the threshold
  p: 0.5106 # ((7.72 + 9.30) / 2) * 0.001 * 60
  q: 1000
  Q: 900

paths:
  green:
    children:
      - blue
      - purple
    distribution:
      - 0.7
      - 0.3
  blue:
    duration: [15, 2]
    children: [white]
  purple:
    children:
      - purple_pink
      - purple_red
    distribution:
      - 0.2
      - 0.8
  purple_pink:
    duration: [10, 1.5]
    children: [pink]
  purple_red:
    duration: [10, 1.5]
    children: [red]
  pink:
    duration: [10, 1.5]
    children: [white]
  red:
    children:
      - stable
      - intensive_care
    distribution: [0.5, 0.5]
  stable:
    children:
      - stable_white
      - stable_black
    distribution: [0.5, 0.5]
  stable_white:
    duration: [10, 3]
    children: [white]
  stable_black:
    duration: [10, 3]
    children: [black]
  intensive_care:
    children:
      - intensive_care_white
      - intensive_care_black
    distribution: [0.5, 0.5]
  intensive_care_white:
    duration: [10, 3]
    children: [white]
  intensive_care_black:
    duration: [10, 3]
    children: [black]
  white: {}
  black: {}

sensitivity:
  params:
    - D_min
    - number_of_patient_zero
  metrics:
    - grouping: blue # a color, sick, infectors or infected
      percent: 20
      # amount: null
      # max_: true
      how: day # amount
    - grouping: sick
      max_: true
      how: amount
  ranges:
    D_min: { step: 5, min: 0, max: 10 }
    D_max: { step: 60, min: 1200, max: 1440 }
    P_max: { step: 0.1, min: 0.1, max: 1.0 }
    number_of_patient_zero: { step: 5, min: 5, max: 15 }
    ITERATIONS: { step: 5, min: 5, max: 20 }
    alpha_blue: { step: 0.1, min: 0.0, max: 1.0 }
