settings:
  PARALLEL: false
  LOCAL_TASK: true
  UPLOAD: false
  SKIP_TESTS: true
  VERBOSE: false
  INCREMENT: false

meta:
  DATASET: copenhagen_groups
  ITERATIONS: 5
  SENSITIVITY: true

params:
  infection_model: 2
  variant_a:
    j: 1
    number_of_patient_zero: 1
    patient_zeroes_on_days: [0]
  # variant_b:
  #   j: 2
  #   number_of_patient_zero: 5
  #   patient_zeroes_on_days: [0]
  D_min: 5
  D_max: 200
  P_max: 0.5

paths:
  green:
    children:
      - blue
      - purple
    distribution:
      - 0.75
      - 0.25
  blue:
    duration: [7.5, 1]
    children: [white]
  purple:
    children:
      - purple_pink
      - purple_red
    distribution:
      - 0.8
      - 0.2
  purple_pink:
    duration: [2.5, 0.5]
    children: [pink]
  purple_red:
    duration: [2.5, 0.5]
    children: [red]
  pink:
    duration: [10, 1]
    children: [white]
  red:
    children:
      - stable
      - intensive_care
    distribution: [0.5, 0.5]
  stable:
    children:
      - stable_white
      - stable_black
    distribution: [0.5, 0.5]
  stable_white:
    duration: [10, 1]
    children: [white]
  stable_black:
    duration: [10, 1]
    children: [black]
  intensive_care:
    children:
      - intensive_care_white
      - intensive_care_black
    distribution: [0.5, 0.5]
  intensive_care_white:
    duration: [10, 1]
    children: [white]
  intensive_care_black:
    duration: [10, 1]
    children: [black]
  white: {}
  black: {}

sensitivity:
  params:
    - green
  metrics:
    - grouping: sick
      how: amount
    - grouping: infected
      how: amount
    - grouping: not_green
      how: amount
  ranges:
    D_min: { step: 5, min: 5, max: 15 }
    D_max: { step: 60, min: 1200, max: 1440 }
    P_max: { step: 0.1, min: 0.3, max: 0.7 }
    number_of_patient_zero: { step: 5, min: 5, max: 15 }
    skew: { step: 3, min: 0, max: 30 }
    ITERATIONS: { step: 5, min: 5, max: 20 }
    alpha_blue: { step: 0.1, min: 0.0, max: 1.0 }
    max_group_size: { step: 2, min: 1000, max: 1000 }
    red: { step: 0.1, min: 0.1, max: 0.3 }
    purple_pink: { step: 0.5, min: 2, max: 3 }
    blue: { step: 0.5, min: 7, max: 8 }
    green: {step: 0.1, min: 0.1, max: 0.3}