settings:
  UPLOAD: false
  VERBOSE: false
  ITER_DATASET: false

meta:
  ITERATIONS: 200
  DATASET: copenhagen_agg
  SENSITIVITY: false

params:
  divide: 3
  infection_model: GroupInfection
  number_of_patient_zero: 6
  patient_zeroes_on_days: [0]
  D_min: 0
  P_max: 0.5

sensitivity:
  change: rows
  params:
    - divide
  # metrics:
  # - grouping: sick
  # - grouping: daily_infected
  #   cumsum: true
  ranges:
    divide:
      step: 1
      min: 1
      max: 3

paths:
  green:
    duration:
      - 2
      - 1
    children:
      - blue
  blue:
    duration:
      - 7
      - 5
    children:
      - white
  white: {}

visualize:
  how:
    - detailed
    # - summary
  metrics:
    - grouping: sick
