settings:
  UPLOAD: true
  VERBOSE: false
  ITER_DATASET: false


meta:
  ITERATIONS: 200
  DATASET: copenhagen_agg
  SENSITIVITY: false

params:
  divide: 2
  infection_model: VariantInfection
  variants: [slow, medium, fast]
  number_of_patient_zero: 1
  D_min: [0, 25, 50]
  P_max: 0.5
  immunity: [1.0, 1.0, 1.0]
  reinfect: 0

sensitivity:
  change: both # both, first, second, default
  params:
    - immunity
  metrics:
    - grouping: sick
    - grouping: daily_infected
      cumsum: true
  ranges:
    immunity: { step: 1.0, min: 0, max: 1}
