copenhagen_groups:
  groups: true
  hops: false
  storage: csv
  real: true
copenhagen_interactions:
  groups: false
  hops: false
  storage: csv
  real: true
milan_calls:
  end_date: '2012-05-31'
  groups: false
  hops: false
  nodes: 7825568
  start_date: '2012-03-26'
  storage: sql
  real: true
mock_data:
  groups: false
  hops: false
  nodes: 4814
  storage: csv
  real: true
half1:
  groups: false
  hops: false
  storage: csv
  real: false
half2:
  groups: false
  hops: false
  storage: csv
  real: false
halfandhalf:
  groups: false
  hops: false
  storage: csv
  real: false
full:
  groups: false
  hops: false
  storage: csv
  real: false
0:
  groups: false
  hops: false
  storage: csv
  real: false
1:
  groups: false
  hops: false
  storage: csv
  real: false
2:
  groups: false
  hops: false
  storage: csv
  real: false
3:
  groups: false
  hops: false
  storage: csv
  real: false
4:
  groups: false
  hops: false
  storage: csv
  real: false
5:
  groups: false
  hops: false
  storage: csv
  real: false
6:
  groups: false
  hops: false
  storage: csv
  real: false
7:
  groups: false
  hops: false
  storage: csv
  real: false
8:
  groups: false
  hops: false
  storage: csv
  real: false
9:
  groups: false
  hops: false
  storage: csv
  real: false
10:
  groups: false
  hops: false
  storage: csv
  real: false
11:
  groups: false
  hops: false
  storage: csv
  real: false
12:
  groups: false
  hops: false
  storage: csv
  real: false
13:
  groups: false
  hops: false
  storage: csv
  real: false
14:
  groups: false
  hops: false
  storage: csv
  real: false
15:
  groups: false
  hops: false
  storage: csv
  real: false
16:
  groups: false
  hops: false
  storage: csv
  real: false
17:
  groups: false
  hops: false
  storage: csv
  real: false
18:
  groups: false
  hops: false
  storage: csv
  real: false
19:
  groups: false
  hops: false
  storage: csv
  real: false
20:
  groups: false
  hops: false
  storage: csv
  real: false
21:
  groups: false
  hops: false
  storage: csv
  real: false
22:
  groups: false
  hops: false
  storage: csv
  real: false
23:
  groups: false
  hops: false
  storage: csv
  real: false
24:
  groups: false
  hops: false
  storage: csv
  real: false
25:
  groups: false
  hops: false
  storage: csv
  real: false
26:
  groups: false
  hops: false
  storage: csv
  real: false
27:
  groups: false
  hops: false
  storage: csv
  real: false
28:
  groups: false
  hops: false
  storage: csv
  real: false
29:
  groups: false
  hops: false
  storage: csv
  real: false
30:
  groups: false
  hops: false
  storage: csv
  real: false
31:
  groups: false
  hops: false
  storage: csv
  real: false
32:
  groups: false
  hops: false
  storage: csv
  real: false
33:
  groups: false
  hops: false
  storage: csv
  real: false