copenhagen_interactions:
  storage: csv
  nodes: 692
  start_date: "2019-12-11"
  end_date: "2020-01-08"
  interval: day
  groups: false
  hops: false
  squeeze: 1
mock_data:
  storage: csv
  nodes: 4814
  start_date: "2012-03-26"
  end_date: "2012-05-31"
  interval: day
  groups: false
  hops: false
  squeeze: 1
copenhagen_hops:
  storage: csv
  nodes: 692
  start_date: "2019-12-11"
  end_date: "2020-01-08"
  interval: day
  groups: false
  hops: false
  squeeze: 1
copenhagen_groups:
  storage: csv
  nodes: 692
  start_date: "2019-12-11"
  end_date: "2020-01-08"
  interval: day
  groups: true
  hops: false
  squeeze: 1
milan_calls:
  storage: sql
  nodes: 7825568
  start_date: "2012-03-26"
  end_date: "2012-05-31"
  interval: day
  groups: false
  hops: false
  squeeze: 1
