copenhagen_groups:
  groups: true
  hops: false
  storage: csv
  real: true
copenhagen_interactions:
  groups: false
  hops: false
  storage: csv
  real: true
milan_calls:
  end_date: '2012-05-31'
  groups: false
  hops: false
  nodes: 7825568
  start_date: '2012-03-26'
  storage: sql
  real: true
mock_data:
  groups: false
  hops: false
  nodes: 4814
  storage: csv
  real: true
half1:
  groups: false
  hops: false
  storage: csv
  real: false
half2:
  groups: false
  hops: false
  storage: csv
  real: false
halfandhalf:
  groups: false
  hops: false
  storage: csv
  real: false
full:
  groups: false
  hops: false
  storage: csv
  real: false
random_undirected:
  groups: false
  hops: false
  storage: csv
  real: false